# Generated by Django 3.0.1 on 2021-03-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
