# Generated by Django 3.0.1 on 2021-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='tag',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
